export const NEXT_PUBLIC_SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
export const NEXT_PUBLIC_SUPABASE_ANON_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

export const DEFAULT_AVATARS_BUCKET = "avatars";

export const emojis: { [index: string]: string } = {
  "😊": "smile",
  "🙃": "upside_down",
  "🤪": "quirky",
  "🤓": "nerd",
  "🤯": "mind_blown",
  "😴": "sleep",
  "💩": "poop",
  "👻": "ghost",
  "👽": "alien",
  "🤖": "robot",
  "👾": "game",
  "👐": "open",
  "🖖": "vulkan",
  "✌️": "peace",
  "🤟": "love",
  "🤘": "rock",
  "🤙": "call",
  "👋": "wave",
  "🐭": "rat",
  "🦕": "dino",
  "🦖": "t_rex",
  "🐉": "dragon",
  "🤡": "clown",
  "🦀": "crab",
  "🦞": "shark",
  "🦐": "jelly",
  "🦑": "snail",
  // transport
  "🚗": "car",
  "🚕": "taxi",
  "🚙": "truck",
  "🚌": "bus",
  "🚎": "tram",
  "🏎": "racing",
  "🚓": "police",
  "🚑": "ambulance",
  "🚒": "fire",
  "🚐": "minibus",
  "🚚": "tractor",
  "🚛": "delivery",
  "🚜": "articulated",
  "🛴": "bicycle",
  "🚲": "bicycle2",
  "🛵": "motorcycle",
  "🏍": "motorcycle2",
  "🚨": "police2",
  "🚔": "oncoming",
  "🚍": "tractor2",
  "🚘": "oncoming2",
  "🚖": "oncoming3",
  "🚡": "aerial_tramway",
  // food
  "🍏": "green_apple",
  "🍎": "apple",
  "🍐": "pear",
  "🍊": "tangerine",
  "🍋": "lemon",
  "🍌": "banana",
  "🍉": "watermelon",
};
